name: Run Tagging and Release

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

permissions:
  contents: write

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/release-npm-package-auto.yml@2f12e0eb5d446e4f36a1247417445beda6ac474e # v0.4.1
